/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: orc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "orc.pb-c.h"
void   orc__proto__integer_statistics__init
                     (Orc__Proto__IntegerStatistics         *message)
{
  static const Orc__Proto__IntegerStatistics init_value = ORC__PROTO__INTEGER_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__integer_statistics__get_packed_size
                     (const Orc__Proto__IntegerStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__integer_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__integer_statistics__pack
                     (const Orc__Proto__IntegerStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__integer_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__integer_statistics__pack_to_buffer
                     (const Orc__Proto__IntegerStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__integer_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__IntegerStatistics *
       orc__proto__integer_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__IntegerStatistics *)
     protobuf_c_message_unpack (&orc__proto__integer_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__integer_statistics__free_unpacked
                     (Orc__Proto__IntegerStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__integer_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__double_statistics__init
                     (Orc__Proto__DoubleStatistics         *message)
{
  static const Orc__Proto__DoubleStatistics init_value = ORC__PROTO__DOUBLE_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__double_statistics__get_packed_size
                     (const Orc__Proto__DoubleStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__double_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__double_statistics__pack
                     (const Orc__Proto__DoubleStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__double_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__double_statistics__pack_to_buffer
                     (const Orc__Proto__DoubleStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__double_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__DoubleStatistics *
       orc__proto__double_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__DoubleStatistics *)
     protobuf_c_message_unpack (&orc__proto__double_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__double_statistics__free_unpacked
                     (Orc__Proto__DoubleStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__double_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__string_statistics__init
                     (Orc__Proto__StringStatistics         *message)
{
  static const Orc__Proto__StringStatistics init_value = ORC__PROTO__STRING_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__string_statistics__get_packed_size
                     (const Orc__Proto__StringStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__string_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__string_statistics__pack
                     (const Orc__Proto__StringStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__string_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__string_statistics__pack_to_buffer
                     (const Orc__Proto__StringStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__string_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__StringStatistics *
       orc__proto__string_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__StringStatistics *)
     protobuf_c_message_unpack (&orc__proto__string_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__string_statistics__free_unpacked
                     (Orc__Proto__StringStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__string_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__bucket_statistics__init
                     (Orc__Proto__BucketStatistics         *message)
{
  static const Orc__Proto__BucketStatistics init_value = ORC__PROTO__BUCKET_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__bucket_statistics__get_packed_size
                     (const Orc__Proto__BucketStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__bucket_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__bucket_statistics__pack
                     (const Orc__Proto__BucketStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__bucket_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__bucket_statistics__pack_to_buffer
                     (const Orc__Proto__BucketStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__bucket_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__BucketStatistics *
       orc__proto__bucket_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__BucketStatistics *)
     protobuf_c_message_unpack (&orc__proto__bucket_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__bucket_statistics__free_unpacked
                     (Orc__Proto__BucketStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__bucket_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__decimal_statistics__init
                     (Orc__Proto__DecimalStatistics         *message)
{
  static const Orc__Proto__DecimalStatistics init_value = ORC__PROTO__DECIMAL_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__decimal_statistics__get_packed_size
                     (const Orc__Proto__DecimalStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__decimal_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__decimal_statistics__pack
                     (const Orc__Proto__DecimalStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__decimal_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__decimal_statistics__pack_to_buffer
                     (const Orc__Proto__DecimalStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__decimal_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__DecimalStatistics *
       orc__proto__decimal_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__DecimalStatistics *)
     protobuf_c_message_unpack (&orc__proto__decimal_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__decimal_statistics__free_unpacked
                     (Orc__Proto__DecimalStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__decimal_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__date_statistics__init
                     (Orc__Proto__DateStatistics         *message)
{
  static const Orc__Proto__DateStatistics init_value = ORC__PROTO__DATE_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__date_statistics__get_packed_size
                     (const Orc__Proto__DateStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__date_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__date_statistics__pack
                     (const Orc__Proto__DateStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__date_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__date_statistics__pack_to_buffer
                     (const Orc__Proto__DateStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__date_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__DateStatistics *
       orc__proto__date_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__DateStatistics *)
     protobuf_c_message_unpack (&orc__proto__date_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__date_statistics__free_unpacked
                     (Orc__Proto__DateStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__date_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__timestamp_statistics__init
                     (Orc__Proto__TimestampStatistics         *message)
{
  static const Orc__Proto__TimestampStatistics init_value = ORC__PROTO__TIMESTAMP_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__timestamp_statistics__get_packed_size
                     (const Orc__Proto__TimestampStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__timestamp_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__timestamp_statistics__pack
                     (const Orc__Proto__TimestampStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__timestamp_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__timestamp_statistics__pack_to_buffer
                     (const Orc__Proto__TimestampStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__timestamp_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__TimestampStatistics *
       orc__proto__timestamp_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__TimestampStatistics *)
     protobuf_c_message_unpack (&orc__proto__timestamp_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__timestamp_statistics__free_unpacked
                     (Orc__Proto__TimestampStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__timestamp_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__binary_statistics__init
                     (Orc__Proto__BinaryStatistics         *message)
{
  static const Orc__Proto__BinaryStatistics init_value = ORC__PROTO__BINARY_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__binary_statistics__get_packed_size
                     (const Orc__Proto__BinaryStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__binary_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__binary_statistics__pack
                     (const Orc__Proto__BinaryStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__binary_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__binary_statistics__pack_to_buffer
                     (const Orc__Proto__BinaryStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__binary_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__BinaryStatistics *
       orc__proto__binary_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__BinaryStatistics *)
     protobuf_c_message_unpack (&orc__proto__binary_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__binary_statistics__free_unpacked
                     (Orc__Proto__BinaryStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__binary_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__column_statistics__init
                     (Orc__Proto__ColumnStatistics         *message)
{
  static const Orc__Proto__ColumnStatistics init_value = ORC__PROTO__COLUMN_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__column_statistics__get_packed_size
                     (const Orc__Proto__ColumnStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__column_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__column_statistics__pack
                     (const Orc__Proto__ColumnStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__column_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__column_statistics__pack_to_buffer
                     (const Orc__Proto__ColumnStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__column_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__ColumnStatistics *
       orc__proto__column_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__ColumnStatistics *)
     protobuf_c_message_unpack (&orc__proto__column_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__column_statistics__free_unpacked
                     (Orc__Proto__ColumnStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__column_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__row_index_entry__init
                     (Orc__Proto__RowIndexEntry         *message)
{
  static const Orc__Proto__RowIndexEntry init_value = ORC__PROTO__ROW_INDEX_ENTRY__INIT;
  *message = init_value;
}
size_t orc__proto__row_index_entry__get_packed_size
                     (const Orc__Proto__RowIndexEntry *message)
{
  assert(message->base.descriptor == &orc__proto__row_index_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__row_index_entry__pack
                     (const Orc__Proto__RowIndexEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__row_index_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__row_index_entry__pack_to_buffer
                     (const Orc__Proto__RowIndexEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__row_index_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__RowIndexEntry *
       orc__proto__row_index_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__RowIndexEntry *)
     protobuf_c_message_unpack (&orc__proto__row_index_entry__descriptor,
                                allocator, len, data);
}
void   orc__proto__row_index_entry__free_unpacked
                     (Orc__Proto__RowIndexEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__row_index_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__row_index__init
                     (Orc__Proto__RowIndex         *message)
{
  static const Orc__Proto__RowIndex init_value = ORC__PROTO__ROW_INDEX__INIT;
  *message = init_value;
}
size_t orc__proto__row_index__get_packed_size
                     (const Orc__Proto__RowIndex *message)
{
  assert(message->base.descriptor == &orc__proto__row_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__row_index__pack
                     (const Orc__Proto__RowIndex *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__row_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__row_index__pack_to_buffer
                     (const Orc__Proto__RowIndex *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__row_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__RowIndex *
       orc__proto__row_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__RowIndex *)
     protobuf_c_message_unpack (&orc__proto__row_index__descriptor,
                                allocator, len, data);
}
void   orc__proto__row_index__free_unpacked
                     (Orc__Proto__RowIndex *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__row_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__bloom_filter__init
                     (Orc__Proto__BloomFilter         *message)
{
  static const Orc__Proto__BloomFilter init_value = ORC__PROTO__BLOOM_FILTER__INIT;
  *message = init_value;
}
size_t orc__proto__bloom_filter__get_packed_size
                     (const Orc__Proto__BloomFilter *message)
{
  assert(message->base.descriptor == &orc__proto__bloom_filter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__bloom_filter__pack
                     (const Orc__Proto__BloomFilter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__bloom_filter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__bloom_filter__pack_to_buffer
                     (const Orc__Proto__BloomFilter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__bloom_filter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__BloomFilter *
       orc__proto__bloom_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__BloomFilter *)
     protobuf_c_message_unpack (&orc__proto__bloom_filter__descriptor,
                                allocator, len, data);
}
void   orc__proto__bloom_filter__free_unpacked
                     (Orc__Proto__BloomFilter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__bloom_filter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__bloom_filter_index__init
                     (Orc__Proto__BloomFilterIndex         *message)
{
  static const Orc__Proto__BloomFilterIndex init_value = ORC__PROTO__BLOOM_FILTER_INDEX__INIT;
  *message = init_value;
}
size_t orc__proto__bloom_filter_index__get_packed_size
                     (const Orc__Proto__BloomFilterIndex *message)
{
  assert(message->base.descriptor == &orc__proto__bloom_filter_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__bloom_filter_index__pack
                     (const Orc__Proto__BloomFilterIndex *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__bloom_filter_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__bloom_filter_index__pack_to_buffer
                     (const Orc__Proto__BloomFilterIndex *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__bloom_filter_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__BloomFilterIndex *
       orc__proto__bloom_filter_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__BloomFilterIndex *)
     protobuf_c_message_unpack (&orc__proto__bloom_filter_index__descriptor,
                                allocator, len, data);
}
void   orc__proto__bloom_filter_index__free_unpacked
                     (Orc__Proto__BloomFilterIndex *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__bloom_filter_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__stream__init
                     (Orc__Proto__Stream         *message)
{
  static const Orc__Proto__Stream init_value = ORC__PROTO__STREAM__INIT;
  *message = init_value;
}
size_t orc__proto__stream__get_packed_size
                     (const Orc__Proto__Stream *message)
{
  assert(message->base.descriptor == &orc__proto__stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__stream__pack
                     (const Orc__Proto__Stream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__stream__pack_to_buffer
                     (const Orc__Proto__Stream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__Stream *
       orc__proto__stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__Stream *)
     protobuf_c_message_unpack (&orc__proto__stream__descriptor,
                                allocator, len, data);
}
void   orc__proto__stream__free_unpacked
                     (Orc__Proto__Stream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__column_encoding__init
                     (Orc__Proto__ColumnEncoding         *message)
{
  static const Orc__Proto__ColumnEncoding init_value = ORC__PROTO__COLUMN_ENCODING__INIT;
  *message = init_value;
}
size_t orc__proto__column_encoding__get_packed_size
                     (const Orc__Proto__ColumnEncoding *message)
{
  assert(message->base.descriptor == &orc__proto__column_encoding__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__column_encoding__pack
                     (const Orc__Proto__ColumnEncoding *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__column_encoding__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__column_encoding__pack_to_buffer
                     (const Orc__Proto__ColumnEncoding *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__column_encoding__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__ColumnEncoding *
       orc__proto__column_encoding__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__ColumnEncoding *)
     protobuf_c_message_unpack (&orc__proto__column_encoding__descriptor,
                                allocator, len, data);
}
void   orc__proto__column_encoding__free_unpacked
                     (Orc__Proto__ColumnEncoding *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__column_encoding__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__stripe_footer__init
                     (Orc__Proto__StripeFooter         *message)
{
  static const Orc__Proto__StripeFooter init_value = ORC__PROTO__STRIPE_FOOTER__INIT;
  *message = init_value;
}
size_t orc__proto__stripe_footer__get_packed_size
                     (const Orc__Proto__StripeFooter *message)
{
  assert(message->base.descriptor == &orc__proto__stripe_footer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__stripe_footer__pack
                     (const Orc__Proto__StripeFooter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__stripe_footer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__stripe_footer__pack_to_buffer
                     (const Orc__Proto__StripeFooter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__stripe_footer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__StripeFooter *
       orc__proto__stripe_footer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__StripeFooter *)
     protobuf_c_message_unpack (&orc__proto__stripe_footer__descriptor,
                                allocator, len, data);
}
void   orc__proto__stripe_footer__free_unpacked
                     (Orc__Proto__StripeFooter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__stripe_footer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__type__init
                     (Orc__Proto__Type         *message)
{
  static const Orc__Proto__Type init_value = ORC__PROTO__TYPE__INIT;
  *message = init_value;
}
size_t orc__proto__type__get_packed_size
                     (const Orc__Proto__Type *message)
{
  assert(message->base.descriptor == &orc__proto__type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__type__pack
                     (const Orc__Proto__Type *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__type__pack_to_buffer
                     (const Orc__Proto__Type *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__Type *
       orc__proto__type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__Type *)
     protobuf_c_message_unpack (&orc__proto__type__descriptor,
                                allocator, len, data);
}
void   orc__proto__type__free_unpacked
                     (Orc__Proto__Type *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__stripe_information__init
                     (Orc__Proto__StripeInformation         *message)
{
  static const Orc__Proto__StripeInformation init_value = ORC__PROTO__STRIPE_INFORMATION__INIT;
  *message = init_value;
}
size_t orc__proto__stripe_information__get_packed_size
                     (const Orc__Proto__StripeInformation *message)
{
  assert(message->base.descriptor == &orc__proto__stripe_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__stripe_information__pack
                     (const Orc__Proto__StripeInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__stripe_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__stripe_information__pack_to_buffer
                     (const Orc__Proto__StripeInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__stripe_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__StripeInformation *
       orc__proto__stripe_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__StripeInformation *)
     protobuf_c_message_unpack (&orc__proto__stripe_information__descriptor,
                                allocator, len, data);
}
void   orc__proto__stripe_information__free_unpacked
                     (Orc__Proto__StripeInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__stripe_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__user_metadata_item__init
                     (Orc__Proto__UserMetadataItem         *message)
{
  static const Orc__Proto__UserMetadataItem init_value = ORC__PROTO__USER_METADATA_ITEM__INIT;
  *message = init_value;
}
size_t orc__proto__user_metadata_item__get_packed_size
                     (const Orc__Proto__UserMetadataItem *message)
{
  assert(message->base.descriptor == &orc__proto__user_metadata_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__user_metadata_item__pack
                     (const Orc__Proto__UserMetadataItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__user_metadata_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__user_metadata_item__pack_to_buffer
                     (const Orc__Proto__UserMetadataItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__user_metadata_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__UserMetadataItem *
       orc__proto__user_metadata_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__UserMetadataItem *)
     protobuf_c_message_unpack (&orc__proto__user_metadata_item__descriptor,
                                allocator, len, data);
}
void   orc__proto__user_metadata_item__free_unpacked
                     (Orc__Proto__UserMetadataItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__user_metadata_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__stripe_statistics__init
                     (Orc__Proto__StripeStatistics         *message)
{
  static const Orc__Proto__StripeStatistics init_value = ORC__PROTO__STRIPE_STATISTICS__INIT;
  *message = init_value;
}
size_t orc__proto__stripe_statistics__get_packed_size
                     (const Orc__Proto__StripeStatistics *message)
{
  assert(message->base.descriptor == &orc__proto__stripe_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__stripe_statistics__pack
                     (const Orc__Proto__StripeStatistics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__stripe_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__stripe_statistics__pack_to_buffer
                     (const Orc__Proto__StripeStatistics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__stripe_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__StripeStatistics *
       orc__proto__stripe_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__StripeStatistics *)
     protobuf_c_message_unpack (&orc__proto__stripe_statistics__descriptor,
                                allocator, len, data);
}
void   orc__proto__stripe_statistics__free_unpacked
                     (Orc__Proto__StripeStatistics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__stripe_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__metadata__init
                     (Orc__Proto__Metadata         *message)
{
  static const Orc__Proto__Metadata init_value = ORC__PROTO__METADATA__INIT;
  *message = init_value;
}
size_t orc__proto__metadata__get_packed_size
                     (const Orc__Proto__Metadata *message)
{
  assert(message->base.descriptor == &orc__proto__metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__metadata__pack
                     (const Orc__Proto__Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__metadata__pack_to_buffer
                     (const Orc__Proto__Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__Metadata *
       orc__proto__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__Metadata *)
     protobuf_c_message_unpack (&orc__proto__metadata__descriptor,
                                allocator, len, data);
}
void   orc__proto__metadata__free_unpacked
                     (Orc__Proto__Metadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__footer__init
                     (Orc__Proto__Footer         *message)
{
  static const Orc__Proto__Footer init_value = ORC__PROTO__FOOTER__INIT;
  *message = init_value;
}
size_t orc__proto__footer__get_packed_size
                     (const Orc__Proto__Footer *message)
{
  assert(message->base.descriptor == &orc__proto__footer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__footer__pack
                     (const Orc__Proto__Footer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__footer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__footer__pack_to_buffer
                     (const Orc__Proto__Footer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__footer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__Footer *
       orc__proto__footer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__Footer *)
     protobuf_c_message_unpack (&orc__proto__footer__descriptor,
                                allocator, len, data);
}
void   orc__proto__footer__free_unpacked
                     (Orc__Proto__Footer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__footer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__post_script__init
                     (Orc__Proto__PostScript         *message)
{
  static const Orc__Proto__PostScript init_value = ORC__PROTO__POST_SCRIPT__INIT;
  *message = init_value;
}
size_t orc__proto__post_script__get_packed_size
                     (const Orc__Proto__PostScript *message)
{
  assert(message->base.descriptor == &orc__proto__post_script__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__post_script__pack
                     (const Orc__Proto__PostScript *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__post_script__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__post_script__pack_to_buffer
                     (const Orc__Proto__PostScript *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__post_script__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__PostScript *
       orc__proto__post_script__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__PostScript *)
     protobuf_c_message_unpack (&orc__proto__post_script__descriptor,
                                allocator, len, data);
}
void   orc__proto__post_script__free_unpacked
                     (Orc__Proto__PostScript *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__post_script__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orc__proto__file_tail__init
                     (Orc__Proto__FileTail         *message)
{
  static const Orc__Proto__FileTail init_value = ORC__PROTO__FILE_TAIL__INIT;
  *message = init_value;
}
size_t orc__proto__file_tail__get_packed_size
                     (const Orc__Proto__FileTail *message)
{
  assert(message->base.descriptor == &orc__proto__file_tail__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orc__proto__file_tail__pack
                     (const Orc__Proto__FileTail *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orc__proto__file_tail__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orc__proto__file_tail__pack_to_buffer
                     (const Orc__Proto__FileTail *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orc__proto__file_tail__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orc__Proto__FileTail *
       orc__proto__file_tail__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orc__Proto__FileTail *)
     protobuf_c_message_unpack (&orc__proto__file_tail__descriptor,
                                allocator, len, data);
}
void   orc__proto__file_tail__free_unpacked
                     (Orc__Proto__FileTail *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &orc__proto__file_tail__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor orc__proto__integer_statistics__field_descriptors[3] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__IntegerStatistics, has_minimum),
    offsetof(Orc__Proto__IntegerStatistics, minimum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__IntegerStatistics, has_maximum),
    offsetof(Orc__Proto__IntegerStatistics, maximum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__IntegerStatistics, has_sum),
    offsetof(Orc__Proto__IntegerStatistics, sum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__integer_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
  2,   /* field[2] = sum */
};
static const ProtobufCIntRange orc__proto__integer_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__integer_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.IntegerStatistics",
  "IntegerStatistics",
  "Orc__Proto__IntegerStatistics",
  "orc.proto",
  sizeof(Orc__Proto__IntegerStatistics),
  3,
  orc__proto__integer_statistics__field_descriptors,
  orc__proto__integer_statistics__field_indices_by_name,
  1,  orc__proto__integer_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__integer_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__double_statistics__field_descriptors[3] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orc__Proto__DoubleStatistics, has_minimum),
    offsetof(Orc__Proto__DoubleStatistics, minimum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orc__Proto__DoubleStatistics, has_maximum),
    offsetof(Orc__Proto__DoubleStatistics, maximum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Orc__Proto__DoubleStatistics, has_sum),
    offsetof(Orc__Proto__DoubleStatistics, sum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__double_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
  2,   /* field[2] = sum */
};
static const ProtobufCIntRange orc__proto__double_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__double_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.DoubleStatistics",
  "DoubleStatistics",
  "Orc__Proto__DoubleStatistics",
  "orc.proto",
  sizeof(Orc__Proto__DoubleStatistics),
  3,
  orc__proto__double_statistics__field_descriptors,
  orc__proto__double_statistics__field_indices_by_name,
  1,  orc__proto__double_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__double_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__string_statistics__field_descriptors[3] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__StringStatistics, minimum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__StringStatistics, maximum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__StringStatistics, has_sum),
    offsetof(Orc__Proto__StringStatistics, sum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__string_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
  2,   /* field[2] = sum */
};
static const ProtobufCIntRange orc__proto__string_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__string_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.StringStatistics",
  "StringStatistics",
  "Orc__Proto__StringStatistics",
  "orc.proto",
  sizeof(Orc__Proto__StringStatistics),
  3,
  orc__proto__string_statistics__field_descriptors,
  orc__proto__string_statistics__field_indices_by_name,
  1,  orc__proto__string_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__string_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__bucket_statistics__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__BucketStatistics, n_count),
    offsetof(Orc__Proto__BucketStatistics, count),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__bucket_statistics__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange orc__proto__bucket_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orc__proto__bucket_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.BucketStatistics",
  "BucketStatistics",
  "Orc__Proto__BucketStatistics",
  "orc.proto",
  sizeof(Orc__Proto__BucketStatistics),
  1,
  orc__proto__bucket_statistics__field_descriptors,
  orc__proto__bucket_statistics__field_indices_by_name,
  1,  orc__proto__bucket_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__bucket_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__decimal_statistics__field_descriptors[3] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__DecimalStatistics, minimum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__DecimalStatistics, maximum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__DecimalStatistics, sum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__decimal_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
  2,   /* field[2] = sum */
};
static const ProtobufCIntRange orc__proto__decimal_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__decimal_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.DecimalStatistics",
  "DecimalStatistics",
  "Orc__Proto__DecimalStatistics",
  "orc.proto",
  sizeof(Orc__Proto__DecimalStatistics),
  3,
  orc__proto__decimal_statistics__field_descriptors,
  orc__proto__decimal_statistics__field_indices_by_name,
  1,  orc__proto__decimal_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__decimal_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__date_statistics__field_descriptors[2] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Orc__Proto__DateStatistics, has_minimum),
    offsetof(Orc__Proto__DateStatistics, minimum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Orc__Proto__DateStatistics, has_maximum),
    offsetof(Orc__Proto__DateStatistics, maximum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__date_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
};
static const ProtobufCIntRange orc__proto__date_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor orc__proto__date_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.DateStatistics",
  "DateStatistics",
  "Orc__Proto__DateStatistics",
  "orc.proto",
  sizeof(Orc__Proto__DateStatistics),
  2,
  orc__proto__date_statistics__field_descriptors,
  orc__proto__date_statistics__field_indices_by_name,
  1,  orc__proto__date_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__date_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__timestamp_statistics__field_descriptors[4] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__TimestampStatistics, has_minimum),
    offsetof(Orc__Proto__TimestampStatistics, minimum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__TimestampStatistics, has_maximum),
    offsetof(Orc__Proto__TimestampStatistics, maximum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minimumUtc",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__TimestampStatistics, has_minimumutc),
    offsetof(Orc__Proto__TimestampStatistics, minimumutc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximumUtc",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__TimestampStatistics, has_maximumutc),
    offsetof(Orc__Proto__TimestampStatistics, maximumutc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__timestamp_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  3,   /* field[3] = maximumUtc */
  0,   /* field[0] = minimum */
  2,   /* field[2] = minimumUtc */
};
static const ProtobufCIntRange orc__proto__timestamp_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor orc__proto__timestamp_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.TimestampStatistics",
  "TimestampStatistics",
  "Orc__Proto__TimestampStatistics",
  "orc.proto",
  sizeof(Orc__Proto__TimestampStatistics),
  4,
  orc__proto__timestamp_statistics__field_descriptors,
  orc__proto__timestamp_statistics__field_indices_by_name,
  1,  orc__proto__timestamp_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__timestamp_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__binary_statistics__field_descriptors[1] =
{
  {
    "sum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Orc__Proto__BinaryStatistics, has_sum),
    offsetof(Orc__Proto__BinaryStatistics, sum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__binary_statistics__field_indices_by_name[] = {
  0,   /* field[0] = sum */
};
static const ProtobufCIntRange orc__proto__binary_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orc__proto__binary_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.BinaryStatistics",
  "BinaryStatistics",
  "Orc__Proto__BinaryStatistics",
  "orc.proto",
  sizeof(Orc__Proto__BinaryStatistics),
  1,
  orc__proto__binary_statistics__field_descriptors,
  orc__proto__binary_statistics__field_indices_by_name,
  1,  orc__proto__binary_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__binary_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__column_statistics__field_descriptors[10] =
{
  {
    "numberOfValues",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__ColumnStatistics, has_numberofvalues),
    offsetof(Orc__Proto__ColumnStatistics, numberofvalues),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intStatistics",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, intstatistics),
    &orc__proto__integer_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "doubleStatistics",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, doublestatistics),
    &orc__proto__double_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stringStatistics",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, stringstatistics),
    &orc__proto__string_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bucketStatistics",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, bucketstatistics),
    &orc__proto__bucket_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decimalStatistics",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, decimalstatistics),
    &orc__proto__decimal_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dateStatistics",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, datestatistics),
    &orc__proto__date_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "binaryStatistics",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, binarystatistics),
    &orc__proto__binary_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestampStatistics",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__ColumnStatistics, timestampstatistics),
    &orc__proto__timestamp_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hasNull",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Orc__Proto__ColumnStatistics, has_hasnull),
    offsetof(Orc__Proto__ColumnStatistics, hasnull),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__column_statistics__field_indices_by_name[] = {
  7,   /* field[7] = binaryStatistics */
  4,   /* field[4] = bucketStatistics */
  6,   /* field[6] = dateStatistics */
  5,   /* field[5] = decimalStatistics */
  2,   /* field[2] = doubleStatistics */
  9,   /* field[9] = hasNull */
  1,   /* field[1] = intStatistics */
  0,   /* field[0] = numberOfValues */
  3,   /* field[3] = stringStatistics */
  8,   /* field[8] = timestampStatistics */
};
static const ProtobufCIntRange orc__proto__column_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor orc__proto__column_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.ColumnStatistics",
  "ColumnStatistics",
  "Orc__Proto__ColumnStatistics",
  "orc.proto",
  sizeof(Orc__Proto__ColumnStatistics),
  10,
  orc__proto__column_statistics__field_descriptors,
  orc__proto__column_statistics__field_indices_by_name,
  1,  orc__proto__column_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__column_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__row_index_entry__field_descriptors[2] =
{
  {
    "positions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__RowIndexEntry, n_positions),
    offsetof(Orc__Proto__RowIndexEntry, positions),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statistics",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__RowIndexEntry, statistics),
    &orc__proto__column_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__row_index_entry__field_indices_by_name[] = {
  0,   /* field[0] = positions */
  1,   /* field[1] = statistics */
};
static const ProtobufCIntRange orc__proto__row_index_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor orc__proto__row_index_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.RowIndexEntry",
  "RowIndexEntry",
  "Orc__Proto__RowIndexEntry",
  "orc.proto",
  sizeof(Orc__Proto__RowIndexEntry),
  2,
  orc__proto__row_index_entry__field_descriptors,
  orc__proto__row_index_entry__field_indices_by_name,
  1,  orc__proto__row_index_entry__number_ranges,
  (ProtobufCMessageInit) orc__proto__row_index_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__row_index__field_descriptors[1] =
{
  {
    "entry",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__RowIndex, n_entry),
    offsetof(Orc__Proto__RowIndex, entry),
    &orc__proto__row_index_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__row_index__field_indices_by_name[] = {
  0,   /* field[0] = entry */
};
static const ProtobufCIntRange orc__proto__row_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orc__proto__row_index__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.RowIndex",
  "RowIndex",
  "Orc__Proto__RowIndex",
  "orc.proto",
  sizeof(Orc__Proto__RowIndex),
  1,
  orc__proto__row_index__field_descriptors,
  orc__proto__row_index__field_indices_by_name,
  1,  orc__proto__row_index__number_ranges,
  (ProtobufCMessageInit) orc__proto__row_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__bloom_filter__field_descriptors[3] =
{
  {
    "numHashFunctions",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__BloomFilter, has_numhashfunctions),
    offsetof(Orc__Proto__BloomFilter, numhashfunctions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitset",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(Orc__Proto__BloomFilter, n_bitset),
    offsetof(Orc__Proto__BloomFilter, bitset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "utf8bitset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Orc__Proto__BloomFilter, has_utf8bitset),
    offsetof(Orc__Proto__BloomFilter, utf8bitset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__bloom_filter__field_indices_by_name[] = {
  1,   /* field[1] = bitset */
  0,   /* field[0] = numHashFunctions */
  2,   /* field[2] = utf8bitset */
};
static const ProtobufCIntRange orc__proto__bloom_filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__bloom_filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.BloomFilter",
  "BloomFilter",
  "Orc__Proto__BloomFilter",
  "orc.proto",
  sizeof(Orc__Proto__BloomFilter),
  3,
  orc__proto__bloom_filter__field_descriptors,
  orc__proto__bloom_filter__field_indices_by_name,
  1,  orc__proto__bloom_filter__number_ranges,
  (ProtobufCMessageInit) orc__proto__bloom_filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__bloom_filter_index__field_descriptors[1] =
{
  {
    "bloomFilter",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__BloomFilterIndex, n_bloomfilter),
    offsetof(Orc__Proto__BloomFilterIndex, bloomfilter),
    &orc__proto__bloom_filter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__bloom_filter_index__field_indices_by_name[] = {
  0,   /* field[0] = bloomFilter */
};
static const ProtobufCIntRange orc__proto__bloom_filter_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orc__proto__bloom_filter_index__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.BloomFilterIndex",
  "BloomFilterIndex",
  "Orc__Proto__BloomFilterIndex",
  "orc.proto",
  sizeof(Orc__Proto__BloomFilterIndex),
  1,
  orc__proto__bloom_filter_index__field_descriptors,
  orc__proto__bloom_filter_index__field_indices_by_name,
  1,  orc__proto__bloom_filter_index__number_ranges,
  (ProtobufCMessageInit) orc__proto__bloom_filter_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue orc__proto__stream__kind__enum_values_by_number[9] =
{
  { "PRESENT", "ORC__PROTO__STREAM__KIND__PRESENT", 0 },
  { "DATA", "ORC__PROTO__STREAM__KIND__DATA", 1 },
  { "LENGTH", "ORC__PROTO__STREAM__KIND__LENGTH", 2 },
  { "DICTIONARY_DATA", "ORC__PROTO__STREAM__KIND__DICTIONARY_DATA", 3 },
  { "DICTIONARY_COUNT", "ORC__PROTO__STREAM__KIND__DICTIONARY_COUNT", 4 },
  { "SECONDARY", "ORC__PROTO__STREAM__KIND__SECONDARY", 5 },
  { "ROW_INDEX", "ORC__PROTO__STREAM__KIND__ROW_INDEX", 6 },
  { "BLOOM_FILTER", "ORC__PROTO__STREAM__KIND__BLOOM_FILTER", 7 },
  { "BLOOM_FILTER_UTF8", "ORC__PROTO__STREAM__KIND__BLOOM_FILTER_UTF8", 8 },
};
static const ProtobufCIntRange orc__proto__stream__kind__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex orc__proto__stream__kind__enum_values_by_name[9] =
{
  { "BLOOM_FILTER", 7 },
  { "BLOOM_FILTER_UTF8", 8 },
  { "DATA", 1 },
  { "DICTIONARY_COUNT", 4 },
  { "DICTIONARY_DATA", 3 },
  { "LENGTH", 2 },
  { "PRESENT", 0 },
  { "ROW_INDEX", 6 },
  { "SECONDARY", 5 },
};
const ProtobufCEnumDescriptor orc__proto__stream__kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "orc.proto.Stream.Kind",
  "Kind",
  "Orc__Proto__Stream__Kind",
  "orc.proto",
  9,
  orc__proto__stream__kind__enum_values_by_number,
  9,
  orc__proto__stream__kind__enum_values_by_name,
  1,
  orc__proto__stream__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor orc__proto__stream__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Orc__Proto__Stream, has_kind),
    offsetof(Orc__Proto__Stream, kind),
    &orc__proto__stream__kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "column",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__Stream, has_column),
    offsetof(Orc__Proto__Stream, column),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__Stream, has_length),
    offsetof(Orc__Proto__Stream, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__stream__field_indices_by_name[] = {
  1,   /* field[1] = column */
  0,   /* field[0] = kind */
  2,   /* field[2] = length */
};
static const ProtobufCIntRange orc__proto__stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__stream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.Stream",
  "Stream",
  "Orc__Proto__Stream",
  "orc.proto",
  sizeof(Orc__Proto__Stream),
  3,
  orc__proto__stream__field_descriptors,
  orc__proto__stream__field_indices_by_name,
  1,  orc__proto__stream__number_ranges,
  (ProtobufCMessageInit) orc__proto__stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue orc__proto__column_encoding__kind__enum_values_by_number[4] =
{
  { "DIRECT", "ORC__PROTO__COLUMN_ENCODING__KIND__DIRECT", 0 },
  { "DICTIONARY", "ORC__PROTO__COLUMN_ENCODING__KIND__DICTIONARY", 1 },
  { "DIRECT_V2", "ORC__PROTO__COLUMN_ENCODING__KIND__DIRECT_V2", 2 },
  { "DICTIONARY_V2", "ORC__PROTO__COLUMN_ENCODING__KIND__DICTIONARY_V2", 3 },
};
static const ProtobufCIntRange orc__proto__column_encoding__kind__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex orc__proto__column_encoding__kind__enum_values_by_name[4] =
{
  { "DICTIONARY", 1 },
  { "DICTIONARY_V2", 3 },
  { "DIRECT", 0 },
  { "DIRECT_V2", 2 },
};
const ProtobufCEnumDescriptor orc__proto__column_encoding__kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "orc.proto.ColumnEncoding.Kind",
  "Kind",
  "Orc__Proto__ColumnEncoding__Kind",
  "orc.proto",
  4,
  orc__proto__column_encoding__kind__enum_values_by_number,
  4,
  orc__proto__column_encoding__kind__enum_values_by_name,
  1,
  orc__proto__column_encoding__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor orc__proto__column_encoding__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Orc__Proto__ColumnEncoding, has_kind),
    offsetof(Orc__Proto__ColumnEncoding, kind),
    &orc__proto__column_encoding__kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dictionarySize",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__ColumnEncoding, has_dictionarysize),
    offsetof(Orc__Proto__ColumnEncoding, dictionarysize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bloomEncoding",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__ColumnEncoding, has_bloomencoding),
    offsetof(Orc__Proto__ColumnEncoding, bloomencoding),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__column_encoding__field_indices_by_name[] = {
  2,   /* field[2] = bloomEncoding */
  1,   /* field[1] = dictionarySize */
  0,   /* field[0] = kind */
};
static const ProtobufCIntRange orc__proto__column_encoding__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__column_encoding__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.ColumnEncoding",
  "ColumnEncoding",
  "Orc__Proto__ColumnEncoding",
  "orc.proto",
  sizeof(Orc__Proto__ColumnEncoding),
  3,
  orc__proto__column_encoding__field_descriptors,
  orc__proto__column_encoding__field_indices_by_name,
  1,  orc__proto__column_encoding__number_ranges,
  (ProtobufCMessageInit) orc__proto__column_encoding__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__stripe_footer__field_descriptors[3] =
{
  {
    "streams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__StripeFooter, n_streams),
    offsetof(Orc__Proto__StripeFooter, streams),
    &orc__proto__stream__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "columns",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__StripeFooter, n_columns),
    offsetof(Orc__Proto__StripeFooter, columns),
    &orc__proto__column_encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writerTimezone",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__StripeFooter, writertimezone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__stripe_footer__field_indices_by_name[] = {
  1,   /* field[1] = columns */
  0,   /* field[0] = streams */
  2,   /* field[2] = writerTimezone */
};
static const ProtobufCIntRange orc__proto__stripe_footer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orc__proto__stripe_footer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.StripeFooter",
  "StripeFooter",
  "Orc__Proto__StripeFooter",
  "orc.proto",
  sizeof(Orc__Proto__StripeFooter),
  3,
  orc__proto__stripe_footer__field_descriptors,
  orc__proto__stripe_footer__field_indices_by_name,
  1,  orc__proto__stripe_footer__number_ranges,
  (ProtobufCMessageInit) orc__proto__stripe_footer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue orc__proto__type__kind__enum_values_by_number[18] =
{
  { "BOOLEAN", "ORC__PROTO__TYPE__KIND__BOOLEAN", 0 },
  { "BYTE", "ORC__PROTO__TYPE__KIND__BYTE", 1 },
  { "SHORT", "ORC__PROTO__TYPE__KIND__SHORT", 2 },
  { "INT", "ORC__PROTO__TYPE__KIND__INT", 3 },
  { "LONG", "ORC__PROTO__TYPE__KIND__LONG", 4 },
  { "FLOAT", "ORC__PROTO__TYPE__KIND__FLOAT", 5 },
  { "DOUBLE", "ORC__PROTO__TYPE__KIND__DOUBLE", 6 },
  { "STRING", "ORC__PROTO__TYPE__KIND__STRING", 7 },
  { "BINARY", "ORC__PROTO__TYPE__KIND__BINARY", 8 },
  { "TIMESTAMP", "ORC__PROTO__TYPE__KIND__TIMESTAMP", 9 },
  { "LIST", "ORC__PROTO__TYPE__KIND__LIST", 10 },
  { "MAP", "ORC__PROTO__TYPE__KIND__MAP", 11 },
  { "STRUCT", "ORC__PROTO__TYPE__KIND__STRUCT", 12 },
  { "UNION", "ORC__PROTO__TYPE__KIND__UNION", 13 },
  { "DECIMAL", "ORC__PROTO__TYPE__KIND__DECIMAL", 14 },
  { "DATE", "ORC__PROTO__TYPE__KIND__DATE", 15 },
  { "VARCHAR", "ORC__PROTO__TYPE__KIND__VARCHAR", 16 },
  { "CHAR", "ORC__PROTO__TYPE__KIND__CHAR", 17 },
};
static const ProtobufCIntRange orc__proto__type__kind__value_ranges[] = {
{0, 0},{0, 18}
};
static const ProtobufCEnumValueIndex orc__proto__type__kind__enum_values_by_name[18] =
{
  { "BINARY", 8 },
  { "BOOLEAN", 0 },
  { "BYTE", 1 },
  { "CHAR", 17 },
  { "DATE", 15 },
  { "DECIMAL", 14 },
  { "DOUBLE", 6 },
  { "FLOAT", 5 },
  { "INT", 3 },
  { "LIST", 10 },
  { "LONG", 4 },
  { "MAP", 11 },
  { "SHORT", 2 },
  { "STRING", 7 },
  { "STRUCT", 12 },
  { "TIMESTAMP", 9 },
  { "UNION", 13 },
  { "VARCHAR", 16 },
};
const ProtobufCEnumDescriptor orc__proto__type__kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "orc.proto.Type.Kind",
  "Kind",
  "Orc__Proto__Type__Kind",
  "orc.proto",
  18,
  orc__proto__type__kind__enum_values_by_number,
  18,
  orc__proto__type__kind__enum_values_by_name,
  1,
  orc__proto__type__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor orc__proto__type__field_descriptors[6] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Orc__Proto__Type, has_kind),
    offsetof(Orc__Proto__Type, kind),
    &orc__proto__type__kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subtypes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__Type, n_subtypes),
    offsetof(Orc__Proto__Type, subtypes),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fieldNames",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Orc__Proto__Type, n_fieldnames),
    offsetof(Orc__Proto__Type, fieldnames),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximumLength",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__Type, has_maximumlength),
    offsetof(Orc__Proto__Type, maximumlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "precision",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__Type, has_precision),
    offsetof(Orc__Proto__Type, precision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__Type, has_scale),
    offsetof(Orc__Proto__Type, scale),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__type__field_indices_by_name[] = {
  2,   /* field[2] = fieldNames */
  0,   /* field[0] = kind */
  3,   /* field[3] = maximumLength */
  4,   /* field[4] = precision */
  5,   /* field[5] = scale */
  1,   /* field[1] = subtypes */
};
static const ProtobufCIntRange orc__proto__type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor orc__proto__type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.Type",
  "Type",
  "Orc__Proto__Type",
  "orc.proto",
  sizeof(Orc__Proto__Type),
  6,
  orc__proto__type__field_descriptors,
  orc__proto__type__field_indices_by_name,
  1,  orc__proto__type__number_ranges,
  (ProtobufCMessageInit) orc__proto__type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__stripe_information__field_descriptors[5] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__StripeInformation, has_offset),
    offsetof(Orc__Proto__StripeInformation, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexLength",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__StripeInformation, has_indexlength),
    offsetof(Orc__Proto__StripeInformation, indexlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataLength",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__StripeInformation, has_datalength),
    offsetof(Orc__Proto__StripeInformation, datalength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "footerLength",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__StripeInformation, has_footerlength),
    offsetof(Orc__Proto__StripeInformation, footerlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numberOfRows",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__StripeInformation, has_numberofrows),
    offsetof(Orc__Proto__StripeInformation, numberofrows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__stripe_information__field_indices_by_name[] = {
  2,   /* field[2] = dataLength */
  3,   /* field[3] = footerLength */
  1,   /* field[1] = indexLength */
  4,   /* field[4] = numberOfRows */
  0,   /* field[0] = offset */
};
static const ProtobufCIntRange orc__proto__stripe_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor orc__proto__stripe_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.StripeInformation",
  "StripeInformation",
  "Orc__Proto__StripeInformation",
  "orc.proto",
  sizeof(Orc__Proto__StripeInformation),
  5,
  orc__proto__stripe_information__field_descriptors,
  orc__proto__stripe_information__field_indices_by_name,
  1,  orc__proto__stripe_information__number_ranges,
  (ProtobufCMessageInit) orc__proto__stripe_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__user_metadata_item__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__UserMetadataItem, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Orc__Proto__UserMetadataItem, has_value),
    offsetof(Orc__Proto__UserMetadataItem, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__user_metadata_item__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange orc__proto__user_metadata_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor orc__proto__user_metadata_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.UserMetadataItem",
  "UserMetadataItem",
  "Orc__Proto__UserMetadataItem",
  "orc.proto",
  sizeof(Orc__Proto__UserMetadataItem),
  2,
  orc__proto__user_metadata_item__field_descriptors,
  orc__proto__user_metadata_item__field_indices_by_name,
  1,  orc__proto__user_metadata_item__number_ranges,
  (ProtobufCMessageInit) orc__proto__user_metadata_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__stripe_statistics__field_descriptors[1] =
{
  {
    "colStats",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__StripeStatistics, n_colstats),
    offsetof(Orc__Proto__StripeStatistics, colstats),
    &orc__proto__column_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__stripe_statistics__field_indices_by_name[] = {
  0,   /* field[0] = colStats */
};
static const ProtobufCIntRange orc__proto__stripe_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orc__proto__stripe_statistics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.StripeStatistics",
  "StripeStatistics",
  "Orc__Proto__StripeStatistics",
  "orc.proto",
  sizeof(Orc__Proto__StripeStatistics),
  1,
  orc__proto__stripe_statistics__field_descriptors,
  orc__proto__stripe_statistics__field_indices_by_name,
  1,  orc__proto__stripe_statistics__number_ranges,
  (ProtobufCMessageInit) orc__proto__stripe_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__metadata__field_descriptors[1] =
{
  {
    "stripeStats",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__Metadata, n_stripestats),
    offsetof(Orc__Proto__Metadata, stripestats),
    &orc__proto__stripe_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__metadata__field_indices_by_name[] = {
  0,   /* field[0] = stripeStats */
};
static const ProtobufCIntRange orc__proto__metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orc__proto__metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.Metadata",
  "Metadata",
  "Orc__Proto__Metadata",
  "orc.proto",
  sizeof(Orc__Proto__Metadata),
  1,
  orc__proto__metadata__field_descriptors,
  orc__proto__metadata__field_indices_by_name,
  1,  orc__proto__metadata__number_ranges,
  (ProtobufCMessageInit) orc__proto__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__footer__field_descriptors[9] =
{
  {
    "headerLength",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__Footer, has_headerlength),
    offsetof(Orc__Proto__Footer, headerlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contentLength",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__Footer, has_contentlength),
    offsetof(Orc__Proto__Footer, contentlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stripes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__Footer, n_stripes),
    offsetof(Orc__Proto__Footer, stripes),
    &orc__proto__stripe_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "types",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__Footer, n_types),
    offsetof(Orc__Proto__Footer, types),
    &orc__proto__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__Footer, n_metadata),
    offsetof(Orc__Proto__Footer, metadata),
    &orc__proto__user_metadata_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numberOfRows",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__Footer, has_numberofrows),
    offsetof(Orc__Proto__Footer, numberofrows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statistics",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orc__Proto__Footer, n_statistics),
    offsetof(Orc__Proto__Footer, statistics),
    &orc__proto__column_statistics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rowIndexStride",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__Footer, has_rowindexstride),
    offsetof(Orc__Proto__Footer, rowindexstride),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writer",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__Footer, has_writer),
    offsetof(Orc__Proto__Footer, writer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__footer__field_indices_by_name[] = {
  1,   /* field[1] = contentLength */
  0,   /* field[0] = headerLength */
  4,   /* field[4] = metadata */
  5,   /* field[5] = numberOfRows */
  7,   /* field[7] = rowIndexStride */
  6,   /* field[6] = statistics */
  2,   /* field[2] = stripes */
  3,   /* field[3] = types */
  8,   /* field[8] = writer */
};
static const ProtobufCIntRange orc__proto__footer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor orc__proto__footer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.Footer",
  "Footer",
  "Orc__Proto__Footer",
  "orc.proto",
  sizeof(Orc__Proto__Footer),
  9,
  orc__proto__footer__field_descriptors,
  orc__proto__footer__field_indices_by_name,
  1,  orc__proto__footer__number_ranges,
  (ProtobufCMessageInit) orc__proto__footer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__post_script__field_descriptors[7] =
{
  {
    "footerLength",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__PostScript, has_footerlength),
    offsetof(Orc__Proto__PostScript, footerlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compression",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Orc__Proto__PostScript, has_compression),
    offsetof(Orc__Proto__PostScript, compression),
    &orc__proto__compression_kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compressionBlockSize",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__PostScript, has_compressionblocksize),
    offsetof(Orc__Proto__PostScript, compressionblocksize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__PostScript, n_version),
    offsetof(Orc__Proto__PostScript, version),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadataLength",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__PostScript, has_metadatalength),
    offsetof(Orc__Proto__PostScript, metadatalength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writerVersion",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Orc__Proto__PostScript, has_writerversion),
    offsetof(Orc__Proto__PostScript, writerversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "magic",
    8000,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__PostScript, magic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__post_script__field_indices_by_name[] = {
  1,   /* field[1] = compression */
  2,   /* field[2] = compressionBlockSize */
  0,   /* field[0] = footerLength */
  6,   /* field[6] = magic */
  4,   /* field[4] = metadataLength */
  3,   /* field[3] = version */
  5,   /* field[5] = writerVersion */
};
static const ProtobufCIntRange orc__proto__post_script__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8000, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor orc__proto__post_script__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.PostScript",
  "PostScript",
  "Orc__Proto__PostScript",
  "orc.proto",
  sizeof(Orc__Proto__PostScript),
  7,
  orc__proto__post_script__field_descriptors,
  orc__proto__post_script__field_indices_by_name,
  2,  orc__proto__post_script__number_ranges,
  (ProtobufCMessageInit) orc__proto__post_script__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orc__proto__file_tail__field_descriptors[4] =
{
  {
    "postscript",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__FileTail, postscript),
    &orc__proto__post_script__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "footer",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Orc__Proto__FileTail, footer),
    &orc__proto__footer__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileLength",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__FileTail, has_filelength),
    offsetof(Orc__Proto__FileTail, filelength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "postscriptLength",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orc__Proto__FileTail, has_postscriptlength),
    offsetof(Orc__Proto__FileTail, postscriptlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orc__proto__file_tail__field_indices_by_name[] = {
  2,   /* field[2] = fileLength */
  1,   /* field[1] = footer */
  0,   /* field[0] = postscript */
  3,   /* field[3] = postscriptLength */
};
static const ProtobufCIntRange orc__proto__file_tail__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor orc__proto__file_tail__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orc.proto.FileTail",
  "FileTail",
  "Orc__Proto__FileTail",
  "orc.proto",
  sizeof(Orc__Proto__FileTail),
  4,
  orc__proto__file_tail__field_descriptors,
  orc__proto__file_tail__field_indices_by_name,
  1,  orc__proto__file_tail__number_ranges,
  (ProtobufCMessageInit) orc__proto__file_tail__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue orc__proto__compression_kind__enum_values_by_number[6] =
{
  { "NONE", "ORC__PROTO__COMPRESSION_KIND__NONE", 0 },
  { "ZLIB", "ORC__PROTO__COMPRESSION_KIND__ZLIB", 1 },
  { "SNAPPY", "ORC__PROTO__COMPRESSION_KIND__SNAPPY", 2 },
  { "LZO", "ORC__PROTO__COMPRESSION_KIND__LZO", 3 },
  { "LZ4", "ORC__PROTO__COMPRESSION_KIND__LZ4", 4 },
  { "ZSTD", "ORC__PROTO__COMPRESSION_KIND__ZSTD", 5 },
};
static const ProtobufCIntRange orc__proto__compression_kind__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex orc__proto__compression_kind__enum_values_by_name[6] =
{
  { "LZ4", 4 },
  { "LZO", 3 },
  { "NONE", 0 },
  { "SNAPPY", 2 },
  { "ZLIB", 1 },
  { "ZSTD", 5 },
};
const ProtobufCEnumDescriptor orc__proto__compression_kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "orc.proto.CompressionKind",
  "CompressionKind",
  "Orc__Proto__CompressionKind",
  "orc.proto",
  6,
  orc__proto__compression_kind__enum_values_by_number,
  6,
  orc__proto__compression_kind__enum_values_by_name,
  1,
  orc__proto__compression_kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
