#pragma once
#include "orc.pb-c.h"


#define ORC__OK                 0
#define ORC__ENOMEM             12
#define ORC__NODECODE           29 
#define ORC__NOSTREAM           30

#define ORC__DECOMPRESS_OK      0
#define ORC__DECOMPRESS_ERR     20

#define ORC__BLOCK_HEADER_SIZE  3


#define ORC__COMPRESSION_KIND__NONE               ORC__PROTO__COMPRESSION_KIND__NONE
#define ORC__COMPRESSION_KIND__ZLIB               ORC__PROTO__COMPRESSION_KIND__ZLIB
#define ORC__COMPRESSION_KIND__SNAPPY             ORC__PROTO__COMPRESSION_KIND__SNAPPY
#define ORC__COMPRESSION_KIND__LZO                ORC__PROTO__COMPRESSION_KIND__LZO
#define ORC__COMPRESSION_KIND__LZ4                ORC__PROTO__COMPRESSION_KIND__LZ4
#define ORC__COMPRESSION_KIND__ZSTD               ORC__PROTO__COMPRESSION_KIND__ZSTD

#define ORC__TYPE_KIND__BOOLEAN                   ORC__PROTO__TYPE__KIND__BOOLEAN
#define ORC__TYPE_KIND__BYTE                      ORC__PROTO__TYPE__KIND__BYTE
#define ORC__TYPE_KIND__SHORT                     ORC__PROTO__TYPE__KIND__SHORT
#define ORC__TYPE_KIND__INT                       ORC__PROTO__TYPE__KIND__INT
#define ORC__TYPE_KIND__LONG                      ORC__PROTO__TYPE__KIND__LONG
#define ORC__TYPE_KIND__FLOAT                     ORC__PROTO__TYPE__KIND__FLOAT
#define ORC__TYPE_KIND__DOUBLE                    ORC__PROTO__TYPE__KIND__DOUBLE
#define ORC__TYPE_KIND__STRING                    ORC__PROTO__TYPE__KIND__STRING
#define ORC__TYPE_KIND__BINARY                    ORC__PROTO__TYPE__KIND__BINARY
#define ORC__TYPE_KIND__TIMESTAMP                 ORC__PROTO__TYPE__KIND__TIMESTAMP
#define ORC__TYPE_KIND__LIST                      ORC__PROTO__TYPE__KIND__LIST
#define ORC__TYPE_KIND__MAP                       ORC__PROTO__TYPE__KIND__MAP
#define ORC__TYPE_KIND__STRUCT                    ORC__PROTO__TYPE__KIND__STRUCT
#define ORC__TYPE_KIND__UNION                     ORC__PROTO__TYPE__KIND__UNION
#define ORC__TYPE_KIND__DECIMAL                   ORC__PROTO__TYPE__KIND__DECIMAL
#define ORC__TYPE_KIND__DATE                      ORC__PROTO__TYPE__KIND__DATE
#define ORC__TYPE_KIND__VARCHAR                   ORC__PROTO__TYPE__KIND__VARCHAR
#define ORC__TYPE_KIND__CHAR                      ORC__PROTO__TYPE__KIND__CHAR

#define ORC__STREAM_KIND__PRESENT                 ORC__PROTO__STREAM__KIND__PRESENT
#define ORC__STREAM_KIND__DATA                    ORC__PROTO__STREAM__KIND__DATA
#define ORC__STREAM_KIND__LENGTH                  ORC__PROTO__STREAM__KIND__LENGTH
#define ORC__STREAM_KIND__DICTIONARY_DATA         ORC__PROTO__STREAM__KIND__DICTIONARY_DATA
#define ORC__STREAM_KIND__DICTIONARY_COUNT        ORC__PROTO__STREAM__KIND__DICTIONARY_COUNT
#define ORC__STREAM_KIND__SECONDARY               ORC__PROTO__STREAM__KIND__SECONDARY
#define ORC__STREAM_KIND__ROW_INDEX               ORC__PROTO__STREAM__KIND__ROW_INDEX
#define ORC__STREAM_KIND__BLOOM_FILTER            ORC__PROTO__STREAM__KIND__BLOOM_FILTER
#define ORC__STREAM_KIND__BLOOM_FILTER_UTF8       ORC__PROTO__STREAM__KIND__BLOOM_FILTER_UTF8

#define ORC__COLUMN_ENCODING_KIND__DIRECT         ORC__PROTO__COLUMN_ENCODING__KIND__DIRECT
#define ORC__COLUMN_ENCODING_KIND__DICTIONARY     ORC__PROTO__COLUMN_ENCODING__KIND__DICTIONARY
#define ORC__COLUMN_ENCODING_KIND__DIRECT_V2      ORC__PROTO__COLUMN_ENCODING__KIND__DIRECT_V2
#define ORC__COLUMN_ENCODING_KIND__DICTIONARY_V2  ORC__PROTO__COLUMN_ENCODING__KIND__DICTIONARY_V2
